// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD27S_1JZSJfxz3C5KpGWJME8UBs_uOli0',
    appId: '1:369717108117:web:174f59b858650a4dde6a9c',
    messagingSenderId: '369717108117',
    projectId: 'chitchat-9e4e9',
    authDomain: 'chitchat-9e4e9.firebaseapp.com',
    storageBucket: 'chitchat-9e4e9.firebasestorage.app',
    measurementId: 'G-P5ZGLPM6CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcS4eqPsJiO0eZ6mcTX5Lq7MkaUTCVAfQ',
    appId: '1:369717108117:android:ce5e9998df9153e5de6a9c',
    messagingSenderId: '369717108117',
    projectId: 'chitchat-9e4e9',
    storageBucket: 'chitchat-9e4e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAURJNKwMRNyBfU0LrB8k3yJzM5a6-uA7E',
    appId: '1:369717108117:ios:b3921e4237ed1bd7de6a9c',
    messagingSenderId: '369717108117',
    projectId: 'chitchat-9e4e9',
    storageBucket: 'chitchat-9e4e9.firebasestorage.app',
    iosBundleId: 'com.example.chitChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAURJNKwMRNyBfU0LrB8k3yJzM5a6-uA7E',
    appId: '1:369717108117:ios:b3921e4237ed1bd7de6a9c',
    messagingSenderId: '369717108117',
    projectId: 'chitchat-9e4e9',
    storageBucket: 'chitchat-9e4e9.firebasestorage.app',
    iosBundleId: 'com.example.chitChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD27S_1JZSJfxz3C5KpGWJME8UBs_uOli0',
    appId: '1:369717108117:web:3ee248066092927fde6a9c',
    messagingSenderId: '369717108117',
    projectId: 'chitchat-9e4e9',
    authDomain: 'chitchat-9e4e9.firebaseapp.com',
    storageBucket: 'chitchat-9e4e9.firebasestorage.app',
    measurementId: 'G-X1FY5Q6CFR',
  );

}